### ISSUE TITLE
Examples run but won't display graphics (Missing material)?

### ISSUE THREAD

**Issue by jfelrod1960** [Renanse/Ardor3D#105]
I haven't run the examples in awhile but tried just now and nothing will display.  I got the following output.  I usually run a git pull whenever I see that a change has been made.

Sep 02, 2022 7:31:36 PM com.ardor3d.example.PropertiesGameSettings load
WARNING: Could not load properties. Creating a new one.
[LWJGL] Version: 3.2.3 build 13
[LWJGL] 	 OS: Windows 10 v10.0
[LWJGL] 	JRE: 17.0.2 amd64
[LWJGL] 	JVM: OpenJDK 64-Bit Server VM v17.0.2+8 by Eclipse Adoptium
[LWJGL] Loading JNI library: lwjgl
[LWJGL] 	Module: org.lwjgl
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\JFE\AppData\Local\Temp\lwjglJFE\3.2.3-build-13\lwjgl.dll
[LWJGL] Warning: Failed to instantiate memory allocator: org.lwjgl.system.jemalloc.JEmallocAllocator. Using the system default.
[LWJGL] MemoryUtil allocator: StdlibAllocator
[LWJGL] Loading library: glfw
[LWJGL] 	Module: org.lwjgl.glfw
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\JFE\AppData\Local\Temp\lwjglJFE\3.2.3-build-13\glfw.dll
[LWJGL] Loading JNI library: lwjgl_opengl
[LWJGL] 	Module: org.lwjgl.opengl
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\JFE\AppData\Local\Temp\lwjglJFE\3.2.3-build-13\lwjgl_opengl.dll
[LWJGL] Loading library: opengl32
[LWJGL] 	Module: org.lwjgl.opengl
[LWJGL] 	opengl32.dll not found in org.lwjgl.librarypath=C:\Users\JFE\AppData\Local\Temp\lwjglJFE\3.2.3-build-13
[LWJGL] 	Loaded from system paths: C:\WINDOWS\system32\opengl32.dll
[LWJGL] Java 10 multiplyHigh enabled
[LWJGL] Java 9 check intrinsics enabled
[LWJGL] Java 10 memcpy enabled
[LWJGL] Java 9 text decoding enabled
Sep 02, 2022 7:31:44 PM com.ardor3d.renderer.lwjgl3.Lwjgl3Renderer <init>
INFO: Lwjgl3Renderer created with a 3.3 context.
Sep 02, 2022 7:31:44 PM com.ardor3d.example.ExampleBase init
INFO: Display Vendor: Intel
Sep 02, 2022 7:31:44 PM com.ardor3d.example.ExampleBase init
INFO: Display Renderer: Intel(R) UHD Graphics 630
Sep 02, 2022 7:31:44 PM com.ardor3d.example.ExampleBase init
INFO: Display Version: 3.3.0 - Build 27.20.100.9664
Sep 02, 2022 7:31:44 PM com.ardor3d.example.ExampleBase init
INFO: Shading Language Version: 3.30 - Build 27.20.100.9664
Sep 02, 2022 7:31:44 PM com.ardor3d.renderer.material.MaterialManager chooseTechnique
WARNING: Mesh sphere (com.ardor3d.scenegraph.shape.Sphere) missing material.  Auto-guessing.
Sep 02, 2022 7:31:45 PM com.ardor3d.renderer.material.MaterialManager chooseTechnique
WARNING: Mesh torus (com.ardor3d.scenegraph.shape.PQTorus) missing material.  Auto-guessing.

**Comment by Renanse** [comment]
iirc, you had this same issue in the past where your build environment was
not copying everything into place during run?

**Comment by jfelrod1960** [comment]
Josh let me find my notes.  I thought I had remedied that problem.  I will close the issue if I find what I did wrong.  Thanks!  Hope all is well?

**Comment by jfelrod1960** [comment]
Josh this is my fault.  I should have specified that the code I was trying to run is CollisionTreeExample.  I wanted to understand more about how Ardor3D processes collisions.  I did not give you enough information.  I see that on line 61 setupLight() overries that in ExampleBase therefore the sphere and torus wasn't displaying because it is an empty method.  I'm guessing you meant to remove it.  I can close this issue if you like?

**Comment by Renanse** [comment]
I've pushed up a fix for that example.  Please test and close if all is well.

**Comment by jfelrod1960** [comment]
Thanks for the fix Josh!  Closing the issue. :)
