### ISSUE TITLE
Question: Ardor3D using Javascript in the animation framework

### ISSUE THREAD

**Issue by jfelrod1960** [Renanse/Ardor3D#107]
Since Javascript will be dropped from the Java ScriptEngine API in future Java versions, what language will replace it? Groovy? :)

**Comment by lasselindqvist** [comment]
It was already removed in Java 15, so with current versions it will already not work.
https://github.com/oracle/graaljs is one option to use nowadays. It does require Java 11+, which I believe the newest Ardor3D versions require as well.

**Comment by Renanse** [comment]
Great question - we only use JavaScript in the animation system for describing animation layers and triggers and such...  I think if I were to redo it, I would probably go with something like YAML instead of a scripting language.  Thoughts?

**Comment by jfelrod1960** [comment]
Josh you have Javascript code calling A3D classes and methods.  Can Yaml do that?

@lasselindqvist Thanks for the reference.

**Comment by Renanse** [comment]
Yes, that's true, a conversion to a descriptive language would change the way the configuration is done (no function calls from the descriptor)

**Comment by icedevjp** [comment]
Nashorn JavaScript engine that was dropped from JDK still exists as an independent project and supports JDK 15+

https://github.com/openjdk/nashorn and [maven](https://mvnrepository.com/artifact/org.openjdk.nashorn/nashorn-core)
