### ISSUE TITLE
Disk mesh not affected when applying rotations

### ISSUE THREAD

**Issue by jfelrod1960** [Renanse/Ardor3D#108]
This is not a critical issue for me, as I were using the disk mesh to show steering targets for my steering behaviors.  I rotated the disk to be flat against the ground.

**Comment by Renanse** [comment]
@jfelrod1960 Can you provide a small, self-contained example of the issue?

**Comment by jfelrod1960** [comment]
@Renanse Are you looking for a screenshot or code snippet?

**Comment by Renanse** [comment]
Just the typical request for a working code example showing the issue you
are experiencing.

**Comment by Renanse** [comment]
@jfelrod1960 Just pinging you on this - was asking for an example because it is not clear what you mean by the mesh not being affected by rotations - are you adding a rotation to the Transform, or trying to apply it to the meshdata directly?  What's the behavior you see vs. what you expect to see?

**Comment by jfelrod1960** [comment]
My apologies Josh!  It was a bug in my code.  Closing the issue.

**Comment by Renanse** [comment]
Ah, no worries!  Hope life is treating you well

**Comment by jfelrod1960** [comment]
No complaints Josh!  Try to take one day at a time.
