### ISSUE TITLE
Is Ardor3D dead?

### ISSUE THREAD

**Issue by xzripper** [Renanse/Ardor3D#113]
I like Ardor3D because this project seems simpler and more logical than JMonkeyEngine. But the last release was 1 year ago and there is no documentation, is the project dead?

**Comment by Renanse** [comment]
I suppose it depends on what you mean by dead. I am not actively working on
improvements these days, but I will respond to bug reports and questions.

**Comment by xzripper** [comment]
Thanks for response. Do you plan to work on this project?

**Comment by Renanse** [comment]
Yes, I have a branch open with several code improvements that I work on as
time allows, and I integrate improvements from users as well.
