### ISSUE TITLE
ContextGarbageCollector to handle shaders

### ISSUE THREAD

**Issue by mazander** [Renanse/Ardor3D#19]
ContextGarbageCollector is not handling shaders. It is only handling textures, VBOs and DisplayLists. In the context loss the shaders stop working, because the new GL context is not having them.

Work arounds:

if(contextChanged) {
    shaderState._needSendShader = true;
    shaderState._programID = -1;
    shaderState.setNeedsRefresh(true);
}

or 

Create a new ShaderState and apply that.

**Comment by Renanse** [comment]
Addressed with commit 978b80f
