### ISSUE TITLE
instancing inconsistencies

### ISSUE THREAD

**Issue by ghost** [Renanse/Ardor3D#70]
I have modified GeometryInstancingExample.java to load a collada file which has a texture with an alpha set. I've noticed everything renders great until the number of models exceeds the InstancingManager max batch size.

In the code attached I load 29 models. If you set that value to 31 and load the example up and compare side by side with the 29 models window you'll notice the textures with an alpha set don't render the same. You have to look close. One is significantly lighter on part of the model.

A code example can be found here:
http://ardor3d.forumatic.com/viewtopic.php?f=10&t=12713

**Comment by Renanse** [comment]
Closing as instancing is now quite a bit different.
