### ISSUE TITLE
UI min text height too aggressive

### ISSUE THREAD

**Issue by mallanmba** [Renanse/Ardor3D#79]
The min height calculated for UILabel is too small to fit text completely - the bottoms of characters like 'y' 'g' are cut off. Also, 'border' around bmfont characters seems to be cut off (see top of 'I' characters, there should be a black border but it seems the white text is touching the bottom of title bar)

![min_height_text](https://user-images.githubusercontent.com/492600/31467630-7ccbe6b8-ae8f-11e7-8727-be69d8cbc7ad.jpg)

**Comment by Renanse** [comment]
I am unable to reproduce this issue on either Windows or Linux.  Is it possible there's some sort of additional user settings that could affect this?  Maybe a font override or screen scaling?

![image](https://user-images.githubusercontent.com/1929435/31729138-c6311f44-b3f3-11e7-9c06-e04be0fcd897.png)

**Comment by Renanse** [comment]
I was able to repro and fix this.  Commit coming shortly.
