### ISSUE TITLE
Unable to resolve problem with dependency

### ISSUE THREAD

**Issue by jfelrod1960** [Renanse/Ardor3D#81]
I get the following error when trying to use Ardor3d as a dependency ...

C:\Users\jfe.CAMPUS\Documents\GitHub\game-tools>gradle build

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find org.eclipse.swt:swt:3650.
  Searched in the following locations:
      https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/swt/swt/3650/swt-3650.pom
      https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/swt/swt/3650/swt-3650-${swt.classifier}.jar
      http://repo.maven.apache.org/maven2/org/eclipse/swt/swt/3650/swt-3650.pom
      http://repo.maven.apache.org/maven2/org/eclipse/swt/swt/3650/swt-3650-${swt.classifier}.jar
      http://jogamp.org/deployment/maven/org/eclipse/swt/swt/3650/swt-3650.pom
      http://jogamp.org/deployment/maven/org/eclipse/swt/swt/3650/swt-3650-${swt.classifier}.jar
      https://swt-repo.googlecode.com/svn/repo/org/eclipse/swt/swt/3650/swt-3650.pom
      https://swt-repo.googlecode.com/svn/repo/org/eclipse/swt/swt/3650/swt-3650-${swt.classifier}.jar
      file:/C:/Users/jfe.CAMPUS/.m2/repository/org/eclipse/swt/swt/3650/swt-3650.pom
      file:/C:/Users/jfe.CAMPUS/.m2/repository/org/eclipse/swt/swt/3650/swt-3650-${swt.classifier}.jar
  Required by:
      project : > com.ardor3d:ardor3d-swt:1.0-SNAPSHOT

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

I'm using Intellij on Windows 10.  I'm including subproject ardor3d-examples so I can use ExampleBase.java until I build my on superclass.

I'm including the repository in the main build.grade class from the Ardor3d project.  If I had to guess I'm thinking you may have a repository in MavenLocal() that is needed for my project.

Thanks
Jeff

**Comment by Renanse** [comment]
Hey Jeff,

Are you using the latest from master?  I am not sure where 3650 is coming from.  The main build.gradle has listed:

> https://swt-repo.googlecode.com/svn/repo/

That's where we grab swt, and we use 4.3 in the build.gradle referenced in the build.gradle for ardor3d-swt:

> compile group: 'org.eclipse.swt', name: 'org.eclipse.swt.gtk.linux.x86_64', version:'4.3'

Now, I will say that I have had to change the linux ref in that line to the windows version.  I'm not sure how to do the platform switch automatically there.

**Comment by jfelrod1960** [comment]
I changed the line in the dependencies block to compile 'org.eclipse.swt:org.eclipse.swt.win32.win32.x86_64:4.3'.  I'm still getting an error when executing gradle build.  I think the only thing I can do is go ahead and build my own ExampleBase.java class.

I will close this issue.
Jeff
