### ISSUE TITLE
Java 11 compatibility

### ISSUE THREAD

**Issue by lasselindqvist** [Renanse/Ardor3D#86]
I see 1.0.0 is not Java 11 compatible, because it depends on JWJGL 2.9.3 which is not Java 11 compatible (AWTGLCanvas class at least is not).

JWJGL 3 seems to be compatible with Java 11 and I see that the master branch is already depending on that version.

Any plans on when a release supporting Java 11 would be ready or are there any open issues that would benefit from contributions?

**Comment by Renanse** [comment]
No current plans as of yet to raise the min Java version from 8.  A release of the current master may come in the next few months, after I have had a chance to rewrite how Ardor3D handles text input.

**Comment by lasselindqvist** [comment]
Yes, building the project 8 makes sense. My concern was just that those builds are compatible with both Java 8 and Java 11. I will test this anyway soon by building the JARs from master branch.
