### ISSUE TITLE
The predicate alwaysFalse always returns true

### ISSUE THREAD

**Issue by gouessej** [Renanse/Ardor3D#88]
TriggerConditions.alwaysFalse() should always return false as its name implies but it does exactly the opposite:
https://github.com/Renanse/Ardor3D/blob/fb4a0f4cd5cd58c38973802c940561510b9a8b1d/ardor3d-core/src/main/java/com/ardor3d/input/logical/TriggerConditions.java#L41

**Comment by Renanse** [comment]
Indeed, thank you!
