### ISSUE TITLE
Release from master

### ISSUE THREAD

**Issue by lasselindqvist** [Renanse/Ardor3D#91]
Any plans to cut a release from master branch? I am eagerly waiting for an "official" release with lwjgl3.

**Comment by Renanse** [comment]
I did not have any imminent plans to release, mostly because I did not see demand for a release.  But happy to start doing so if useful.

**Comment by lasselindqvist** [comment]
It would be helpful. We have forked the master branch and built artifacts from it, but it would be nicer to have upstream releases.

**Comment by jimbok8** [comment]
Yes, please.
Jim

**Comment by Renanse** [comment]
We finally have a 1.5.X release.  Sorry for the long wait.
