### ISSUE TITLE
Support for Geometry Instancing

### ISSUE THREAD

**Issue by mattikannala** [Renanse/Ardor3D#92]
Implement support for Geometry Instancing.
The support was removed during the major refactoring.

The instancing manager is still there:
https://github.com/Renanse/Ardor3D/blob/master/ardor3d-core/src/main/java/com/ardor3d/scenegraph/InstancingManager.java

Looks like this needs to be implemented in the Mesh.render method.

**Comment by Renanse** [comment]
I will re-add this soon using instanced arrays.
