### ISSUE TITLE
Looks like gradle cannot get the value from ${platform} when trying to run CompoundTerrainExample.

### ISSUE THREAD

**Issue by jfelrod1960** [Renanse/Ardor3D#94]
Execution failed for task ':ardor3d-examples:CompoundTerrainExample.main()'.
> Could not resolve all files for configuration ':ardor3d-examples:runtimeClasspath'.
   > Could not find lwjgl-opengl-3.2.3-natives-${platform}.jar (org.lwjgl:lwjgl-opengl:3.2.3).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opengl/3.2.3/lwjgl-opengl-3.2.3-natives-${platform}.jar
   > Could not find lwjgl-3.2.3-natives-${platform}.jar (org.lwjgl:lwjgl:3.2.3).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/3.2.3/lwjgl-3.2.3-natives-${platform}.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by Renanse** [comment]
This is the latest from trunk? Can you help me understand where we still have ${platform} in our gradle files?

**Comment by jfelrod1960** [comment]
Sorry Josh!  My wife had to go to the hospital.  I will delete my copy from my computer and download again.  Maybe something didn't work right from the git pull command.

**Comment by Renanse** [comment]
Very sorry to hear that, I hope she is in better health now!

**Comment by jfelrod1960** [comment]
Josh where is this statement coming from?  I mean what is it not seeing to get this.  What I did was included all subprojects into my own project except ardor3d-examples.  I copied ExampleBase into my own project and use it to extend my examples.  But to no avail.

Could not find lwjgl-opengl-natives-${platform}.jar (org.lwjgl:lwjgl-opengl:3.2.3).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opengl/3.2.3/lwjgl-opengl-3.2.3-natives-${platform}.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by Renanse** [comment]
Can you do a search for ${platform} and tell me where you see that showing
up?

**Comment by jfelrod1960** [comment]
Josh when I commented these two lines:
//    implementation "com.ardor3d:ardor3d-lwjgl3-awt:${ardor3dVersion}"
//    implementation "com.ardor3d:ardor3d-tools:${ardor3dVersion}"

The "Could not find lwjgl-opengl-natives-${platform}.jar (org.lwjgl:lwjgl-opengl:3.2.3" no longer show.  But I'm still digging.
Also note that this occurs with 1.5.1 and not with 1.0.4.
Jeff

**Comment by Renanse** [comment]
I think you are running into an issue I had tried to patch back in January
and reverted later to avoid hosting my own jar file.  See commit
5914b1526d5f1177684c425fadd58ea08db91ac8 and the end of this pom file:
https://github.com/LWJGLX/lwjgl3-awt/blob/master/pom.xml

**Comment by jfelrod1960** [comment]
Cool.  Should I close this issue?

**Comment by Renanse** [comment]
There may be a more elegant way to handle lwjgl3-awt's sub-dependencies for your situation, but I'll close this for now.

**Comment by Renanse** [comment]
@jfelrod1960 FWIW, I recently discovered lwjgl3-awt had pushed an update moving their binary dependencies to test only.  I've updated Ardor3D (bed099a) to use this version and that may help solve the issue you faced.
