### ISSUE TITLE
PSSM Example Deprecated

### ISSUE THREAD

**Issue by jfelrod1960** [Renanse/Ardor3D#98]
Just curious to know why Parallel Split Shadow Maps got phased out?  I hadn't played with it much, but had plans to.

Thanks!
Jeff

**Comment by Renanse** [comment]
Hi Jeff, the old "draw over" PSSM technique was phased out in favor of a better, general lighting model that includes shadow support.  I still use the PSSM technique for directional shadows, etc.  Please see these examples: https://github.com/Renanse/Ardor3D/tree/master/ardor3d-examples/src/main/java/com/ardor3d/example/lighting

**Comment by jfelrod1960** [comment]
Gotcha!  Thanks! :)
